"""Pywowcher - A Wowcher API integration for Python."""

__title__ = "pywowcher"
__description__ = "A Wowcher API integration for Python."
__url__ = "http://github.com/lukeshiner/pywowcher.git"
__version__ = "0.1"
__release__ = "0.1.0-alpha.1"
__author__ = "Luke Shiner"
__author_email__ = "luke@lukeshiner.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Luke Shiner"
